Section Footer
kgrebets/goit-markup-english-school pull request #14
Opened 2024-12-19 10:35 UTC by Notalama

![image](https://github.com/user-attachments/assets/71df2312-7432-41f7-8a90-647e9099bf61)
![image](https://github.com/user-attachments/assets/1c6ee545-281d-4573-82b5-b172bbb04d5b)

2024-12-19 17:40 UTC, kgrebets requested changes

2024-12-19 17:40 UTC, kgrebets commented on src/css/footer.css
> +  font-weight: 700;
тут заміни на font-weight: var(--weight-bold);

2024-12-19 17:40 UTC, kgrebets commented on src/css/footer.css
> +  color: #fff;
і тут змінну заюзай

2024-12-19 17:40 UTC, kgrebets commented on src/css/footer.css
> +@media screen and (min-width: 1158px) {
а що це за брекпоінт? у нас 1280 усюди був

2024-12-19 22:14 UTC, Notalama commented on src/css/footer.css
> +  color: #fff;
що саме?
тільки білий колір бачу вже є, то замінив

2024-12-20 08:39 UTC, kgrebets approved these changes

2024-12-20 08:39 UTC, merged